export const OWLIA_GUARD_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_owliaOperator',
        type: 'address',
        internalType: 'address',
      },
      { name: '_multisend', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'MULTISEND',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'OWLIA_OPERATOR',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'checkAfterExecution',
    inputs: [
      { name: 'txHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'success', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'checkTransaction',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
      {
        name: 'operation',
        type: 'uint8',
        internalType: 'enum Enum.Operation',
      },
      { name: 'safeTxGas', type: 'uint256', internalType: 'uint256' },
      { name: 'baseGas', type: 'uint256', internalType: 'uint256' },
      { name: 'gasPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'gasToken', type: 'address', internalType: 'address' },
      {
        name: 'refundReceiver',
        type: 'address',
        internalType: 'address payable',
      },
      { name: 'signatures', type: 'bytes', internalType: 'bytes' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserValidator',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multisend',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owliaOperator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setValidator',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'validator', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ValidatorSet',
    inputs: [
      {
        name: 'sender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'validator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'InvalidOwliaMultisendApprovals', inputs: [] },
  { type: 'error', name: 'InvalidOwliaMultisendSubTx', inputs: [] },
  { type: 'error', name: 'InvalidOwliaMultisendSubTxData', inputs: [] },
  {
    type: 'error',
    name: 'InvalidOwliaMultisendSubTxOperation',
    inputs: [],
  },
  { type: 'error', name: 'InvalidOwliaMultisendSubTxTo', inputs: [] },
  {
    type: 'error',
    name: 'InvalidOwliaMultisendSubTxValue',
    inputs: [],
  },
  { type: 'error', name: 'InvalidOwliaMultisendTx', inputs: [] },
  { type: 'error', name: 'InvalidOwliaMultisendTxData', inputs: [] },
] as const;
